const competenze = [
{id: 0, name:"action oriented"},
{id: 1, name:"dealing with ambiguity"},
{id: 2, name:"approachability"},
{id: 3, name:"boss relationships"},
{id: 4, name:"building effective teams"},
{id: 5, name:"business acumen"},
{id: 6, name:"career ambition"},
{id: 7, name:"caring about direct reports"},
{id: 8, name:"comfort around higher management"},
{id: 9, name:"command skills"},
{id: 10, name:"compassion"},
{id: 11, name:"composure"},
{id: 12, name:"conflict management"},
{id: 13, name:"confronting direct reports"},
{id: 14, name:"creativity"},
{id: 15, name:"customer focus"},
{id: 16, name:"decision quality"},
{id: 17, name:"dealing with paradoxes"},
{id: 18, name:"delegation"},
{id: 19, name:"developing direct reports and others"},
{id: 20, name:"directing others"},
{id: 21, name:"drive for results"},
{id: 22, name:"ethics and values"},
{id: 23, name:"fairness to direct reports"},
{id: 24, name:"functional or technical skills"},
{id: 25, name:"hiring and staffing"},
{id: 26, name:"humor"},
{id: 27, name:"informing"},
{id: 28, name:"innovation management"},
{id: 29, name:"integrity and trust"},
{id: 30, name:"intellectual horsepower"},
{id: 31, name:"interpersonal savvy"},
{id: 32, name:"learning on the fly"},
{id: 33, name:"listening"},
{id: 34, name:"managerial courage"},
{id: 35, name:"managing and measuring work"},
{id: 36, name:"managing diversity"},
{id: 37, name:"managing vision and purpose"},
{id: 38, name:"managing through systems"},
{id: 39, name:"motivating others"},
{id: 40, name:"negotiating"},
{id: 41, name:"organizational agility"},
{id: 42, name:"organizing"},
{id: 43, name:"patience"},
{id: 44, name:"peer relationships"},
{id: 45, name:"perseverance"},
{id: 46, name:"personal disclosure"},
{id: 47, name:"personal learning"},
{id: 48, name:"perspective"},
{id: 49, name:"planning"},
{id: 50, name:"political savvy"},
{id: 51, name:"presentation skills"},
{id: 52, name:"priority settings"},
{id: 53, name:"problem solving"},
{id: 54, name:"process management"},
{id: 55, name:"self-development"},
{id: 56, name:"self-knowledge"},
{id: 57, name:"sizing up people"},
{id: 58, name:"standing alone"},
{id: 59, name:"strategic agility"},
{id: 60, name:"technical learning"},
{id: 61, name:"time management"},
{id: 62, name:"timely decision making"},
{id: 63, name:"total work systems"},
{id: 64, name:"understanding others"},
{id: 65, name:"work/life balance"},
{id: 66, name:"written communication"},
]

export default competenze